### ISSUE TITLE
empty form labels for date sliders

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprtradedash#103]
the date sliders below plots need to have a label added. I suspect a label will also be needed for all the other UI elements in `djprshiny::djpr_plot_server`

**Comment by annett-djpr** [comment]
what kind of label?

**Comment by annett-djpr** [comment]
It's working now. This can be closed following approval of my pull request on djprshiny.

**Comment by annett-djpr** [comment]
PR approved.
