### ISSUE TITLE
General: use annual comparisons/changes

### ISSUE THREAD

**Issue by Louis-DJPR** [djpr-data/djprtradedash#17]

**Comment by Louis-DJPR** [comment]
We would prefer that annual comparisons be used as often as possible (instead of monthly or quarterly comparisons). Especially for BoP data, specifying the percentage change over the year to September quarter 2021 c.f. the previous year to September quarter 2020.

**Comment by Emma-DJPR** [comment]
I will change the chart title to reflect the annual comparison

**Comment by Emma-DJPR** [comment]
The issue has been resolved
