### ISSUE TITLE
BOP: change december 2019 as the reference point for comparisons

### ISSUE THREAD

**Issue by Louis-DJPR** [djpr-data/djprtradedash#30]

**Comment by Louis-DJPR** [comment]
There are several charts that compare to December 2019. This is becoming less and less relevant as we recover from COVID. Year-over-year comparisons are more useful. For example, it would be better to say “Victoria’s services exports are x% lower over the year to September quarter 2021 compared to the previous year” (i.e. the year to September quarter 2020).

**Comment by MattDepas** [comment]
Completed
