### ISSUE TITLE
General: Load speed improvements

### ISSUE THREAD

**Issue by Louis-DJPR** [djpr-data/djprtradedash#31]
At present the trade dashboard is taking close to 2 minutes to load on opening, in order to avoid users potentially thinking the dashboard is not working, we should address the speed before wider release.

**Comment by Louis-DJPR** [comment]
Amended sysdata.rda file, app now loads much more quickly but it will be better to transition to a db infrastructure in the long run

**Comment by Henry-DJPR** [comment]
Database now in dev
