### ISSUE TITLE
General: Line chart labels not showing units

### ISSUE THREAD

**Issue by Louis-DJPR** [djpr-data/djprtradedash#40]
There is currently an issue where the end labels for line charts are not showing the units of the values. E.g. "1.9" instead of "1.9%". A proposed source for this issue lies in the `djpr_ts_linechart()` function of the `djprshiny` package as the charts were working as intended prior to the change to the function.

**Comment by Louis-DJPR** [comment]
Alternative: make formatting consistent, if there are subtitles, perhaps we can ignore the units in the label if the units are clearly expressed in the subtitle.

**Comment by Henry-DJPR** [comment]
fixed in dev
