### ISSUE TITLE
Check package dependencies

### ISSUE THREAD

**Issue by Henry-DJPR** [djpr-data/djprtradedash#9]
There's a lengthy list of dependencies but I think a bunch like readsdmx aren't being used. Probably need to check through them all and cull all unused.

**Comment by Henry-DJPR** [comment]
Also while working in the description file, could somebody please update the Authors

**Comment by MattCowgill** [comment]
`readsdmx` is used to get data from the ABS API https://github.com/djpr-data/djprtradedash/blob/c1a9032d7fcb9d0834fef0ac8c1545f908150abd/R/read_merch.R#L62

**Comment by Henry-DJPR** [comment]
All checked an necessary
