### ISSUE TITLE
Update BOP charts to accept lazy data

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprtradedash#92]
the BOP charts are notyet set up to accept lazy data frames. The general process is similar to below code. Pleasae use the launchpad functions as a rough quide. https://github.com/djpr-data/djprtradedash/blob/dev/R/viz_launchpad.R#L30

```
  df <- filtered %>%
    dplyr::filter(.data$country_dest %in% top_5_country) %>%
    dplyr::select(country_dest, origin, date, value)


  if ('tbl_lazy' %in% class(df)) {
    df <- df %>%
      dplyr::collect()
  }
```

**Comment by Emma-DJPR** [comment]
Ten out of eleven visualisations in viz_bop now accepted lazy dash; I have difficulties with viz_vic_total_bop_cumul_line. Can anyone who reviews the task can address the problem, please?
