### ISSUE TITLE
Update all UI fonts to VIC font

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprtradedash#94]
All fonts on a government page need to be VIC font. For now the easiest way to do this will be via CSS. 

As all the charts are svg from ggiraph they are ope to styling. For example chart titles are class `shiny-text-output shiny-bound-output`. Use these classes to set the font face. In the CSS file it will be something like:

``` 
shiny-text-output, shiny-bound-output {
font-family:'vic-regular' sans-serif;
}
```

**Comment by duyjpr** [comment]
Implemented in `djprshiny::djpr_dash_theme` (branch: ui_but_sexier)
