### ISSUE TITLE
Replicate DJPR standard, corporate wenpage footer

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprtradedash#96]
This footer will be required for all pages. But only used if app is **NOT** embedded in iframe

**Comment by mrjoh3** [comment]
for now we just need a quick and easy fix, just in case this is needed. Perhaps try create simple html copy of footer and add via

```
shiny::includeHTML()
```

**Comment by Henry-DJPR** [comment]
No longer needed as dashboards will be embedded via iframe
